server:
  port: 4050

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: guest
    password: guest

sms:
  aliyun:
    accessKey: accessKey
    secretKey: secretKey
    channels:
      loginCodeChannel: SMS_34630023
